### ISSUE TITLE
cabal install not working

### ISSUE THREAD

**Issue by erlandsona** [blaenk/blaenk.github.io#3]
I forked and cloned the repo to make use of some of the haskell you built around hot-module loading (as it would be called in the React.js / webpack world), hoping I could extend it to work on css and js as well.

That said, I'm honestly still a bit of a newb and I can't seem to get the project to compile. I've tried just running a `cabal install` but that returns a bunch of unresolved dependency errors.

So I tried `stack init`, `stack init --solver`, but neither of those worked, and I'm still getting the hang of how Haskell manages dependencies, so I'm not really sure what to do to get stack to build the project?

**Comment by blaenk** [comment]
I don't use this hakyll setup myself anymore. I've been working on a static site generator for Rust and have been dogfooding that for a while.

Unless you're very encouraged to learn Haskell I can't in good faith recommend picking up Hakyll much less a very customized setup like mine, otherwise it'll constantly feel like you're fighting it.

Also being familiar with React.js/webpack, I have to say that things wont be as flexible out of the box (or indeed without much work involved) in Hakyll. Personally I would take the practical route and stick with something in the React.js/webpack realm if you're more familiar with that and have expectations of functionality similar to what that provides.

That said, while I don't maintain this setup anymore, a people have had success by cherry-picking this commit https://github.com/da-x/hakyll-site/commit/c0d82f8e0330de2044a4bfa6d326dd11aefbd3ff which adapts it to allow usage with stack and updates some of the packages. That should fix your problems or at least provide you with a starting point.

I wish you the best!

**Comment by erlandsona** [comment]
I’ve been meaning to reply for a few days now.

First of all, thank you so much for this response. To address your point, I’m pretty much just build this with Hakyll as a fun project to help build my Haskell experience. I realize that a node based build tool would probably do the job better, but you mentioned using green-threads to connect to web sockets for this “hot-swapping” which is such a cool implementation, I’m really hoping I can learn to extend it.

I’ll checkout that commit to fix the stack stuff, thank you for that by the way.

Thanks again!

**Comment by blaenk** [comment]
I believe I merged these fixes with https://github.com/blaenk/blaenk.github.io/commit/3d0781cf8c155f8138190e64cffbbcad67e6db22
